server:
  servlet:
    context-path: /api/v1
  port: 8070

spring:
  application:
    name: ms-biblicoteca
  datasource:
    url: jdbc:postgresql://localhost:5432/BD_BIBLIOTECA_FINAL?currentSchema=bd_biblioteca2
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 3
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: bd_biblioteca2
    open-in-view: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
  secret: Z3VlcmJhLWRlbC1zZWNyZXRvLWRlLWlkYXQtZ2VzdGlvbi1iaWJsaW90ZWNhLTIwMjY=
  expiration: 3600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    pre-loading-enabled: true

logging:
  level:
    pe.edu.idat: DEBUG
    org.springframework.security: DEBUG # Cambia INFO a DEBUG aquí
    org.springframework.web: DEBUG

    org:
      springframework:
        security: INFO


        security=DEBUG: